### PR TITLE
feat: :sparkles: Added Landmarks

### LINKED ISSUE #2: Feature Request: more flexible choice of waypoints
"Say your folders go from A -> B -> C. If you put a waypoint in the folder note of folder A, it'd include every file within folders A, B, and C. But if you create another waypoint in folder B, the first waypoint would only link to that folder note."

This is a great idea, but it's not so flexible.
As it is now, if I want to have a index on B, but still show all content of B in the index on A, I can't.
So, what about having two different flags, one that only generate the index (for example %% Index %%), and one that generates the index and actually marks a waypoint (for example %% Waypoint %%)?
In this way, I could put %% Waypoint %% in A and %% Index %% in B, and get what I wanted: index both in A and in B, and the index in A showing also all the content of B :)

### PR DESCRIPTION
**Pull request by ironman820**
I created a "landmark" feature to provide an index without stopping waypoint generation below it.

Resolves #2 

The .editorconfig changes are optional and only help Markdown follow more widely accepted guidelines. Those and a majority of the README are just formatting updates performed by my formatter. The actual addition to the README starts at line 22 with **INTRODUCING: Landmarks!**. This gives a basic explanation of the new feature set based on your original descriptions.

As for the actual code:

- I added settings and constants to handle "Landmarks"
- I renamed `detectWaypointFlag` to `detectFlag`; `printWaypointError` to `printError`; `updateWaypoint` to `updatePoint`; `updateParentWaypoint` to `updateParentPoint`; `locateParentWaypoint` to `locateParentPoint` to make the naming more function agnostic and open for both Waypoints and Landmarks.
- `detectFlags` now needs to be run twice (once for waypoints and once for landmarks), so I created a `detectFlags` function as a single-call wrapper that invokes the detect command for both Waypoints and Landmarks.
- I have pulled the Landmark and Waypoint creation flag out of the percent signs in the settings editor. It still looks for the same content, but now adds the percent checks codewise.
- Point functions call `setBeginPoint`, `setEndPoint`, and `setPostFlag` when needed to tie the correct constants/settings when looking for the `_BEGIN`, `_END`, and `settings.*Flag` options respectively.
- `updateParentPoint` First searches for the flag (waypoint vs landmark using `locateParentFlag`) in the parents, then searches for the file based on that flag. Once the found instance is updated, it will continue to recursively call itself for each folder up to the root to be able to refresh the entire tree if a user switches between a waypoint and a landmark. *I am just realizing that this implementation of the recursion may not work for the OutsideFolder methodology.*
- All other changes at this point appear to be cosmetic and part of my code formatter (Prettier) creating line breaks and moving small sections indentations.

### CODE REVIEW

**Comment by ironman820** [comment]
I merged `locateParentPoint` and `locateParentFlag` into a single function to reduce redundantly running the same code for individual functions. I also did a little bit of refactoring to reduce nesting where possible. Features remain the same and ran fine in my test Vault.

**Comment by vonlaughing** [comment]
> I merged `locateParentPoint` and `locateParentFlag` into a single function to reduce redundantly running the same code for individual functions. I also did a little bit of refactoring to reduce nesting where possible. Features remain the same and ran fine in my test Vault.

Thank you! Great feature!

One thing I found with this is that the folder notes generated in Landmark mode doesn't follow the "Use WikiLinks" option when turned on. It uses the []() format instead.

**Comment by flawnn** [comment]
W Pull Request, checked out locally and seems fire!

**Comment by IdreesInc** [comment]
This is insane work, sorry for getting to it almost a year late! I hadn't realized how many people were using this plugin until recently as I was caught up with other projects. Currently reviewing the code, need to manage a few conflicts but otherwise this is an amazingly well done PR. Definitely appreciate the documentation of what you changed as well, since the prettier format added a lot of changes. Going to need to take some time to get through this and also maybe find a way to get prettier to stop splitting stuff into different lines, thanks again!

**Comment by IdreesInc** [comment]
Code has been reviewed and is overall brilliant! I did have to make a few changes for whatever reason, here they are listed below:

- Removed changes to settings where "%%" were no longer used in the value field. This would not be backwards compatible with settings made by users previously. While I could add some code stripping the percentages from user's previous settings, I also find that making the user type out the percent symbols makes it more clear what the flag should look like at a glance.

Minor: 

- Switched to using an enum to differentiate waypoint types
- Categorized landmarks as another type of waypoint in the code rather than a separate kind of index
- Changed the wording of things such as the settings
- Removed markdown formatting changes to the readme. While you are likely correct that the spaces are recommended instead of tabs, there isn't really a reason to change it at this point and the diff was quite large. Will consider using spaces for markdown files in the future

Thank you again so much for doing all of this, I know the recursive folder logic is a pain so I appreciate you going through it to make landmarks work. I will be merging the PR with my additional changes and this feature will be added to the next release!

**Pull request merged**
